### ISSUE TITLE
Small typo?

### ISSUE THREAD

**Issue by chrismessina** [w3c/web-locks#105]
On this [line](https://github.com/w3c/web-locks/blob/526a0fe22baceca415d0b327774f0f0e400a92fb/index.bs#L107), should it read:

`await do_something_else();`

instead of 

`await do_somethng_else();`

?

That is, is "something" intentionally misspelled?

**Comment by inexorabletash** [comment]
Not intentional, thanks for the typo catch.

**Comment by inexorabletash** [comment]
Thanks @chrismessina !

FWIW, I ran the .bs file through `ispell` and at least that didn't find other spelling errors.
