### ISSUE TITLE
TPAC 2022 status report

### ISSUE THREAD

**Issue by inexorabletash** [w3c/web-locks#111]
Hey @ljwatson @marcoscaceres @siusin 

This spec wasn't included in https://github.com/w3c/webappswg/issues/87 but per https://github.com/w3c/web-locks/issues/84#issue-1032605561 this is part of the WG charter. Do y'all want a status report? 

cc: @saschanaz

**Comment by inexorabletash** [comment]
Also, potential topics:

* Brainstorming with anyone present on wording around Storage integration, i.e. https://github.com/w3c/web-locks/pull/75 
* Brainstorming around integration with Storage Buckets
* Brainstorming around behavior when storage is cleared (related to above)
* Any needed discussion around back/forward cache integration https://github.com/w3c/web-locks/issues/81
* Behavior with throttling [twitter thread](https://twitter.com/aboodman/status/1549590251558936577) cc: @aboodman
*

**Comment by aboodman** [comment]
Sorry I'm not sure what (if anything) is being asked of me here.

**Comment by marcoscaceres** [comment]
@inexorabletash, sorry for the oversight! Thanks for adding topics and will be sure to put it on the agenda.

**Comment by inexorabletash** [comment]
Sorry @aboodman - no action needed from you. I saw your Twitter thread and wanted to ACK it and discuss getting browser behaviors documented/standardized.

**Comment by inexorabletash** [comment]
# 2022 Status Report

## Progress in the last 12 months

* Moved from WICG to WebApps WG :tada: 
* Added @saschanaz as editor :partying_face: 

Normative changes:

* #79 
* #85 
* #86 
* #96 

Editorial changes:

* Lots of algorithm refactoring and fixes
* More use of [Infra](https://infra.spec.whatwg.org/) concepts

Implementer updates:

* Shipped in :fox_face: Firefox 96 (late 2021). Would love to hear from Mozilla about any implementation challenges, any spec/test issues, etc. 
* Shipped in :compass: Safari 15 (early 2022). Would love to hear from Apple about same. 
* Chromium is exploring integration with [Storage Buckets](https://github.com/WICG/storage-buckets/blob/gh-pages/explainer.md)

Active PRs:

* #75 

Expected near future work:

* #81 
* #77 
* #107
* #108
* Integration with [Storage Buckets](https://github.com/WICG/storage-buckets/blob/gh-pages/explainer.md)
* Define behavior when storage is cleared (related to above)
* Define behavior with respect to page throttling 

## Moving to CR/Rec

* Need to get to FPWD first!

@saschanaz - did I miss anything? Will you be attending TPAC (virtually or physically) and anything you want to schedule time to discuss?

**Comment by saschanaz** [comment]
>did I miss anything? Will you be attending TPAC (virtually or physically) and anything you want to schedule time to discuss?

I think I have nothing specific to talk about. I won't be physically at TPAC but maybe virtually.

**Comment by siusin** [comment]
Web Locks is not part of the W3C [/TR](https://www.w3.org/TR/) documents yet. Look forward to publishing it as a First Public Working Draft. Please let us know when the spec is ready :)

**Comment by marcoscaceres** [comment]
@saschanaz, @inexorabletash, all good for us to send a publication request for FPWD?

**Comment by inexorabletash** [comment]
No blockers I'm aware of.

**Comment by saschanaz** [comment]
Fixing #75 first would be ideal, but that's not blocking IMO.

**Comment by marcoscaceres** [comment]
Thanks @inexorabletash and @saschanaz. 

@siusin, filed https://github.com/w3c/web-locks/issues/112 and send [email to public-webapps](https://lists.w3.org/Archives/Public/public-webapps/2022OctDec/0013.html). Closing.
