### ISSUE TITLE
Call for Consensus: publish First Public Working Draft 

### ISSUE THREAD

**Issue by marcoscaceres** [w3c/web-locks#112]
This is a call for consensus (CFC) to publish the Web Locks API specification as a First Public Working Draft.

The CFC ends at midnight 31 December, 2022.

Please indicate your support for publishing the specification as a W3C First Public Working Draft using either the 👍 or 👎 (formal objection) reaction buttons. 

If you have a formal objection (i.e., you indicate 👎) to its publication, we kindly ask that you raise it before 31 December, 2022.

If approved, it will be published at the following URL:
https://www.w3.org/TR/web-locks/

The API is actively being implemented in all major browser engines and, [judging by the test results on WPT](https://wpt.fyi/results/web-locks), has fairly good interoperability.

(NB: [email to public-webapps](https://lists.w3.org/Archives/Public/public-webapps/2022OctDec/0013.html))

**Comment by siusin** [comment]
This CfC ends with support. 

Thanks all.
