### ISSUE TITLE
Prefix steal with unsafe?

### ISSUE THREAD

**Issue by annevk** [w3c/web-locks#52]
We have some sort of practice of explicitly labeling footguns in CSP. Consider reusing that here?

**Comment by inexorabletash** [comment]
Dang, wish we'd noted that earlier. We already shipped in Chrome, so I'll need to gather usage metrics. Probably safe to change to `unsafeSteal`

**Comment by saschanaz** [comment]
Can this still happen?

**Comment by bathos** [comment]
This seems pretty odd to me, it's not unsafe in the same sense as "unsafe-eval". It's entirely particular to your application's semantics.

**Comment by saschanaz** [comment]
[The design principle](https://w3ctag.github.io/design-principles/#naming-unsafe) says "features that weaken the guarantees provided to developers", and per [the caution](https://wicg.github.io/web-locks/#ref-for-dom-lockoptions-steal) I think that applies here.

**Comment by bathos** [comment]
What guarantee is being weakened? The locks API guarantees that only one exclusive lock is granted at a time and stealing doesn't change that - it just means there is more than one way to end an existing lock.

For example, we use it here:

> Here you need steal so that if there’s a prompt for platform credentials open in one client when they click “sign in with Windows Hello” (etc) in another client, the other one’s lock is lost.

How would "unsafe" do anything but discourage (entirely safe, UX-improving) patterns like that?

**Comment by saschanaz** [comment]
> without guarantees that it is the sole context with access to the resource

This kind of guarantee. Maybe too abstract, yeah, some revision would help in that case.

**Comment by bathos** [comment]
The Locks API never provided that guarantee in the first place is what I think is a key missing point that makes this warning very confusing.

**Comment by saschanaz** [comment]
https://wicg.github.io/web-locks/#concept-lock

>A lock represents exclusive access to a shared resource.

I think the term "resource" in this spec means something more abstract than the actual resource the code uses. Or maybe I'm just confused..

**Comment by bathos** [comment]
I think you're reading it correctly, that is how it's used in the spec. It's just that if `steal` in considered unsafe in practice, so is the entire UnsafeWebLocks API, and it should be `unsafeRequest` too :)

**Comment by saschanaz** [comment]
To be fair I'm just saying that the current phrases in the spec makes me think the design principle applies here, since the phrase for `steal` does say it break some guarantee.

So I guess the work item here is either:

* Revise that paragraph to prevent confusion if such guarantee doesn't exist anyway
* Or, if it actually exists, `unsafeSteal`.

**Comment by saschanaz** [comment]
My current understanding is that:

1. The spec says a lock represents an exclusive access to a resource (as an abstract concept)
2. `steal` breaks that by stealing held locks, and that makes the given locks do not represent exclusive accesses anymore
3. So it does break a guarantee, or at least a general expectation.

**Comment by bathos** [comment]
Right, except that I believe the spec is wrong because it subtly swaps abstract for concrete resource in the warning text. The abstract resource guarantee holds, only the concrete resource guarantee is lost - but it never existed; whether or not the concrete resource is actually guaranteed depends on application semantics always. So if steal is unsafe, so is every other method.

**Comment by saschanaz** [comment]
> the original lock is gone when it is stolen. the promise rejects with an AbortError.

```js
navigator.locks.request("foo", async lock => {
  console.log("Got the resource access");
  await new Promise(resolve => setTimeout(resolve, 1000));
  console.log("Am I still have the exclusive access?"); // expectation broken by `steal`
});
navigator.locks.request("foo", { steal: true }, console.log);
```

You're right that the promise rejects, but it does not stop the callback from running. In this example the second log call runs even when the released promise is rejected.

An imaginary footgun scenario: a dev may write a callback thinking that the resource access is always exclusive while running the callback, later the same dev adds `steal` call with a perfectly valid UX reason, and then they find the previous assumption is broken "by the API design".

**Comment by bathos** [comment]
That is the hazard which I'm suggesting is no different from the fact that they could also later not use steal _or locks at all_ to do the thing-which-was supposed-to-be-exclusive. Web Locks cannot provide any guarantee about that without solving the halting problem, so it seems wrong to me that the note would conflate the abstract resource (still guaranteed by Web Locks) with the concrete one (never guaranteed by Web Locks). Note that the footgun above also exists if you use the signal option (unsafeSignal?).

**Comment by annevk** [comment]
The thing is that if you use locks correctly and haven't used steal, you can have a perfectly logical setup. The moment you (or someone else on your team) starts using steal it can have an impact on a completely different part of the code base. The "unsafe" label would make that somewhat apparent and hopefully trigger an audit of sorts.

Anyway, I'm okay with closing this as it's somewhat cosmetic.

**Comment by saschanaz** [comment]
This is way too late as there now are two implementations with `steal`, even if we can ever reach a consensus to change it. I guess we can safely close this, what do you think? @inexorabletash

**Comment by inexorabletash** [comment]
SGTM. I liked the suggestion but it came in after we shipped in Chrome and adding an alias/deprecating was never a priority.
