### ISSUE TITLE
Replace Origin references with Storage Key

### ISSUE THREAD

**Issue by inexorabletash** [w3c/web-locks#74]
https://storage.spec.whatwg.org/#storage-keys

**Comment by inexorabletash** [comment]
On further thought, passing storage keys around doesn't make as much sense as acquiring the shelf/bucket/bottle directly.

**Comment by smaug----** [comment]
Curious, what is the reasoning here? Doesn't this possibly limit Web Locks to be used with storage stuff only?

**Comment by inexorabletash** [comment]
It's ~always been the case that locks needed to have the same privacy characteristics as storage and APIs like BroadcastChannel. That is, if third party storage is partitioned, locks and channels are partitioned the same way. There didn't used to be a way to specify this, so the spec primarily used "origin" and then had a note in prose that it should match the partitioning behavior of storage. Now that these are defined in Storage, this can be made explicit.

I can't find the detailed discussions at the moment, but some previous issues. 

https://github.com/WICG/web-locks/issues/15
https://github.com/WICG/web-locks/issues/45

Anyway, this shouldn't be a behavior change, just specifying the existing behavior.

**Comment by smaug----** [comment]
ok. Though BroadcastChannel uses origin (per spec at least), which is why I wondered why this change.

**Comment by inexorabletash** [comment]
BroadcastChannel should update too. I'll follow up about a bug. Note that currently a StorageKey is defined as an origin so there's no normative behavior difference until that changes.

**Comment by inexorabletash** [comment]
https://github.com/whatwg/html/issues/5803 I guess serves as this.
