### ISSUE TITLE
Throwing a thenable object in locks.requests callback will implicitly invoke its `.then()`

### ISSUE THREAD

**Issue by ryanwang522** [w3c/web-locks#77]
Hi @inexorabletash , I have a question about throwing a "thenable" object (or returning a rejected promise with thenable object) in the web-locks api callback. "thenable" means that the object defines its .then() method.

Consider the following code,
```
var thenable = { 
    then: (...args) => { console.log("In thenable.then"); } 
} 

navigator.locks.request("lock-test", {mode: "exclusive"}, async () => {
    throw thenable; 
    // or return Promise.reject(thenable);
}).then((res) => console.log(res), (e) => console.log(e));
```
I am wondering is this an expected behavior?

Didn't find any spec mentioning this behavior. One might related is that if we return(resolve) a "thenable" object inside promise chain, it will unpack it by calling `.then`. It will call all `.then`'s until it gets raw value.

I'm using Chrome 91.0.4472.106 (Official Build) (64-bit) on ubuntu 18.04.

**Comment by bathos** [comment]
I suspect you’ve found a Chromium bug. Neither Web IDL nor the internal ECMA-262 promise operations that Web IDL delegates to would access properties / invoke methods of a rejected Promise’s “reason” value — as you said, only fulfilling should lead to “unpacking”. I don’t think Web Locks is supposed to be doing anything unique in this regard.

**Comment by inexorabletash** [comment]
Agreed, looks like a Chrome bug. Can you file one via new.crbug.com ?

**Comment by ryanwang522** [comment]
@bathos Thanks for your clarification. 
I've filed a ticket at https://bugs.chromium.org/p/chromium/issues/detail?id=1250253.

I am investigating chromium source code which might relates to the issue, will update on the above ticket if I found something suspicious, thanks guys :)

**Comment by inexorabletash** [comment]
Thanks. I made a note in the crbug about where to look in the code. 

I'll leave this open for a bit; we should have a WPT for this.

**Comment by ryanwang522** [comment]
(More detail in crbug)
Since the async callback always returns a promise (in pending / fulfilled / rejected state) and we will  later call `ScriptPromise::Then()` with the `Lock::ThenFunction` as its onFulfilled/onRejected callback, possible cases would be like:

- **Case 0 - async callback returns a *pending* promise**
    
    Nothing happens, wait for it to get fulfilled / rejected
    
- **Case 1 - async callback returns a promise *fulfilled* with `value`**
    
    Lock::ThenFunction will be called and `resolve_type_` will be set to `Fulfilled`, so it will resolve the promise that going to returned from `navigator.locks.request()` with `value`. Thus, if `value` is a thenable object, it's `.then` will be invoked once to decide the final state and the [[PromiseResult]] of the return promise.
    
- **Case 2 - async callback returns a promise *rejected* with `value`**
    
    Lock::ThenFunction will be called and `resolve_type_` will be set to `Rejected`, so it will reject the promise that going to returned from the `navigator.locks.request()` with `value`.   This *won't* invoke the `.then` of `value` if it's a thenable object (since we're rejecting).
    However in this issue, we also return the thenable `value` in the onRejected callback (`Lock::ThenFunction::Call`). This would lead to the resolving process which invokes the `.then` of `value` to further determine the [[PromiseResult]] of the promise resolved by the onRejected handler. Its flow is similar to the following code snippet:
    ```jsx
    var thenable = { then: (...args) => { console.log("In thenable.then: ", args); } }
    Promise.reject(thenable).then(
	     v => v, (e) => { 
	     console.log("onRejected ", e); 
	     return e; // this leads to promise resolving process
	   })
    ```

    ```cpp
    ScriptValue Call(ScriptValue value) override {
      (...)
      return value; // this leads to promise resolving process
    }
    ```
    
Moreover, return value of `Lock::ThenFunction::Call(ScriptValue value)` would be wrapped as the resolved value of a new ScriptPromise which returned from `ScriptPromise::Then()` . And in lock api implementation, returned promise from `ScriptPromise::Then()` has never been used.

```cpp
void Lock::HoldUntil(ScriptPromise promise, ScriptPromiseResolver* resolver) {
  DCHECK(!resolver_);

  ScriptState* script_state = resolver->GetScriptState();
  resolver_ = resolver;
  // the promise return from Then() is ignored.
  promise.Then(
      ThenFunction::CreateFunction(script_state, this, ThenFunction::Fulfilled),
      ThenFunction::CreateFunction(script_state, this, ThenFunction::Rejected));
}
```

Therefore, make `Lock::ThenFunction::Call(ScriptValue value)`  return a dummy `ScriptValue` (It wont be further use) instead of return the `value` (no matter it's thenable object or not) when the `resolve_type_` is `Rejected` could prevent the unpacking behavior.

```cpp
ScriptValue Call(ScriptValue value) override {
  DCHECK(lock_);
  DCHECK(resolve_type_ == Fulfilled || resolve_type_ == Rejected);
  lock_->ReleaseIfHeld();
  if (resolve_type_ == Fulfilled)
    lock_->resolver_->Resolve(value);
  else
    lock_->resolver_->Reject(value);
  lock_ = nullptr;
  return resolve_type_ == Rejected ? ScriptValue() : value; // return value;
}
```
Any feedback or advice?

**Comment by saschanaz** [comment]
Can this be closed then?

**Comment by ryanwang522** [comment]
May I know what's the expected behavior of the to-do WPT from your perspective?
IIUC, the WPT should make sure that the then method of a thenable object should not be called when throwing/rejecting it from the async lock callback. For example:
```
  const test_thenable = { 
    then: (...args) => { 
      assert_unreached('Unexpected resolution of thenable object');
    }
  };
  const p = navigator.locks.request(res, async lock => { 
    throw test_thenable;
  });
```
However, this issue need to be fixed in `Lock::ThenFunction` first to meet the above behavior.

**Comment by saschanaz** [comment]
That test makes sense to me.

**Comment by inexorabletash** [comment]
Chromium CL up at https://chromium-review.googlesource.com/4064307 that includes a WPT

**Comment by inexorabletash** [comment]
The test case should be upstreamed soon, so closing this.
