### ISSUE TITLE
Transferring to W3C GitHub org?

### ISSUE THREAD

**Issue by marcoscaceres** [w3c/web-locks#84]
As this will be a deliverable of the web apps wg (new charter effective 1st of Jan 2022), there is the possibility to transfer this repo over to the Github W3C org now with an "unofficial" status... alternatively, we can keep it here until 2022, which is totally fine too. 

Let me know what you'd like to do. Irrespective, it would be good to start preparing for the move by making sure links will point to the "github.org/w3c/" space and start to set up any redirects that might be needed - along with anything else. 

Let me know how you want to proceed.

**Comment by saschanaz** [comment]
Since it's recently frequently me that adds some activity here, I think I won't be too disrupted by the transfer.

**Comment by inexorabletash** [comment]
Yeah, now that we're past TPAC I'm good with a move whenever

**Comment by marcoscaceres** [comment]
ok, can you please transfer ownership to me? I'll then transfer it over to the W3C org.

**Comment by marcoscaceres** [comment]
Oh! if needed, can you please also have a PR ready with any WICG links changed to W3C?

**Comment by inexorabletash** [comment]
I had to temporarily transfer the repo from WICG to my account (github has a limitation?)

Anyway, I've sent the request to transfer to marcoscaceres.

**Comment by inexorabletash** [comment]
ping @marcoscaceres in hopes this happens soon!

**Comment by marcoscaceres** [comment]
@inexorabletash done! Sorry for the delay. Was traveling.
