### ISSUE TITLE
Add Kagami Sascha Rosylight as editor

### ISSUE THREAD

**Issue by inexorabletash** [w3c/web-locks#88]
@saschanaz - do you want to put up a PR for this, or should I? And/or do you want to wait for the spec to migrate to WebApps WG ?

**Comment by saschanaz** [comment]
>And/or do you want to wait for the spec to migrate to WebApps WG?

Yup. I'll send a PR when that happens 👍

**Comment by saschanaz** [comment]
I'm okay with being an editor since Mozilla just shipped this API. Writing a PR...
