### ISSUE TITLE
Clean up work following move to W3C

### ISSUE THREAD

**Issue by inexorabletash** [w3c/web-locks#99]
* [x] https://github.com/w3c/web-locks/blob/main/w3c.json lists repo-type as "cg-report"
* [x] https://labs.w3.org/repo-manager/repos still includes wicg/web-locks not w3c/web-locks
* [x] Create redirect from https://wicg.github.io/web-locks ([docs](https://gist.github.com/domenic/1f286d415559b56d725bee51a62c24a7))
* [x] Anything related to Reffy?
* [x] Update links in WPT https://github.com/web-platform-tests/wpt/pull/31799
* [x] Spec still says "Draft Community Group Report" (`Status: CG-DRAFT` &rarr; `ED`)

**Comment by inexorabletash** [comment]
cc: @saschanaz @marcoscaceres

**Comment by inexorabletash** [comment]
cc: @cwilso

**Comment by inexorabletash** [comment]
cc: @siusin 

Thanks in advance, everyone!

**Comment by saschanaz** [comment]
https://github.com/WICG/wicg.github.io/commit/ed7da4fdcfd2fbb5ecde7fb2ffae57e261d63394 Thanks!

**Comment by saschanaz** [comment]
@inexorabletash For repo-manager thing, could you try https://labs.w3.org/repo-manager/repo/import ? Somehow it fails on my side and not sure this is me or the tool.

**Comment by inexorabletash** [comment]
I'm getting: `/repo-manager/api/import-repo:1 Failed to load resource: the server responded with a status of 500`

**Comment by saschanaz** [comment]
500 is indeed very suspicious! Just checked the network tab and same here. I was totally confused by the console message: `Uncaught (in promise) Invariant Violation: Dispatch.dispatch(...): Cannot dispatch in the middle of a dispatch.`

**Comment by saschanaz** [comment]
Filed https://github.com/w3c/ash-nazg/issues/234

**Comment by inexorabletash** [comment]
FYI I'll update links in the WPTs via https://chromium-review.googlesource.com/c/chromium/src/+/3308509

**Comment by cwilso** [comment]
So, I  hit update in the repo manager to try to solve " https://labs.w3.org/repo-manager/repos still includes wicg/web-locks not w3c/web-locks" - it now has it associated with the right group, but still has the old URL.  I'm not sure I can fix that; maybe Marcos can.

**Comment by saschanaz** [comment]
That list looks quite outdated btw, it still has wicg/web-share 🤔

**Comment by saschanaz** [comment]
For Reffy I guess it should happen automatically but potentially can be accelerated:

1. https://github.com/w3c/validate-repos should be first updated (daily autoupdate should do that)
2. https://github.com/w3c/browser-specs should then be updated by that, this happens weekly
3. Reffy then will get the updated browser-specs dependency

**Comment by inexorabletash** [comment]
WPT updates got hung up on a flake: https://github.com/web-platform-tests/wpt/pull/31799

**Comment by marcoscaceres** [comment]
Just a minor thing... we are still waiting for final approval of the new Web Apps Charter. Just assume it's all good for now, but there will be a couple of little systems hiccups until the charter goes through. That should hopefully happen in a week or two 🤞.

**Comment by saschanaz** [comment]
w3c/validate-repos got w3c/locks https://github.com/w3c/validate-repos/commit/31d1f1eef24426f48c519cb9fb2cba0f566fca40

**Comment by saschanaz** [comment]
* w3c/browser-specs got w3c/web-locks https://github.com/w3c/browser-specs/pull/444, still should wait for another release
* WICG entry is removed https://github.com/WICG/admin/pull/148

**Comment by saschanaz** [comment]
Reffy has w3c/web-locks, I guess everything is done?

**Comment by inexorabletash** [comment]
Go team!
